development:
  adapter: postgresql
  encoding: unicode
  database: zoonoses
  pool: 5
  username: postgres
  password: umasenha

test:
  adapter: postgresql
  encoding: unicode
  database: zoonoses
  pool: 5
  username: postgres
  password: umasenha